# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

env:
  global:
    - PATH="$HOME/miniconda/bin:$PATH"
    - RETICULATE_PYTHON="$HOME/miniconda/bin/python"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
  - pip install --user phate

install:
  - R -e 'devtools::install_deps(dependencies = T)'
  - if [[ $TRAVIS_R_VERSION_STRING == 'devel']; then R -e 'devtools::install_dev_deps(dependencies = T)'; fi

warnings_are_errors: true
