# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
  - pip install --user phate

warnings_are_errors: true
